New gifs
LHL-FocusPocus/FocusPocus pull request #123
Opened 2020-05-23 19:43 UTC by xynyx

Replaced some of the current gifs, cleaned up a few more files & console.logs, deleted unused files.

2020-05-23 23:34 UTC, jpqy requested changes
The options page gif is well done and clear, did you use a different program for that gif? Because the dashboard gif (and navbar) has weird artifacts and shimmering going on. I'd also try to shorten the dashboard gif, right now it's close to 50 megabytes. For example, I don't think it should take 5 seconds to dismiss the toast message at the beginning.

2020-05-23 23:34 UTC, jpqy commented on README.md
> +s
Typo

2020-05-24 14:52 UTC, xynyx reviewed
Made those changes; fixed typo.

Also added open graph image and title so displaying on LinkedIn will show our logo instead of a blank image.

2020-05-24 15:35 UTC, jpqy approved these changes

2020-05-24 16:38 UTC, merged